### PR TITLE
Clublife

### PR DESCRIPTION
**Pull request by 97yogitha**
Clublife is one of the static pages.

### CODE REVIEW

**Comment by abhijithanilkumar** [comment]
@97yogitha Add only the files you've changed. Do not use `git add .`. Don't commit .pyc files and log files. Only add those files that you've changed to the commit.

**Comment by 97yogitha** [comment]
@abhijithanilkumar how do i make the changes now?

**Comment by 97yogitha** [comment]
@rohitvarkey I am unable to display images if there are saved in a local folder. Let me know what need to be done.

**Comment by abhijithanilkumar** [comment]
Check this [link](http://stackoverflow.com/questions/18357511/git-remove-commited-file-after-push). And images has to be stored in the folder mentioned as `MEDIA_ROOT` in the settings.py file.

**Comment by abhijithanilkumar** [comment]
@97yogitha Or you can just remove the unwanted files and commit again. Like [this](https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-git-repo) :stuck_out_tongue:

**Comment by rohitvarkey** [comment]
@97yogitha As @abhijithanilkumar mentioned, the image file needs to go [here](https://github.com/IE-NITK/NITK-Student-Council-Website/tree/master/src/static/site/img). 

The Django docs will help you understand how to access it then https://docs.djangoproject.com/en/1.9/howto/static-files/

**Comment by 97yogitha** [comment]
screenshot 
screenshot from 2016-01-11 19 26 11

**Comment by 97yogitha** [comment]
This is for the hobby clubs need to add more cards..

screenshot from 2016-01-11 19 27 49

**Comment by 97yogitha** [comment]
@jaidevanoop I added jumbotron look into it. But there is an issue i cant center the  buttons. Let me know what needs to be done.

**Comment by rohitvarkey** [comment]
@97yogitha Delete local branch, do a git pull and you'll be set. Get that tech club thing enabled by default and this will be ready for a merge!

Good work! :+1:!

**Comment by 97yogitha** [comment]
@rohitvarkey Changed the tech block to default

**Comment by rohitvarkey** [comment]
@97yogitha Merged! :smile:

**Pull request merged**
