### PR TITLE
Added calendar

### PR DESCRIPTION
**Pull request by vidit23**
This is just the basic layout of the calendar, I tried using blocks but it just doesn't seem to work. Any ideas??
The events need to be fetched from the database in the form of a JSON object.

### CODE REVIEW

**Comment by rohitvarkey** [comment]
@vidit23 did you try putting the `<script>` tags in the `scripts` block?

**Comment by rohitvarkey** [comment]
Is this ready for a merge? @abhijithanilkumar @vidit23

**Comment by abhijithanilkumar** [comment]
@rohitvarkey This is ready for merge now. I've added links to the events. Once the Events page and views are complete, this should work fine. :smile:

**Comment by abhijithanilkumar** [comment]
@rohitvarkey Is it better to have a ```url``` field in the ```model``` which is populated at the time of object creation?

**Comment by rohitvarkey** [comment]
@abhijithanilkumar You mean like a slug? That'd be nice I think. We won't be giving out ids then. :stuck_out_tongue:

**Comment by abhijithanilkumar** [comment]
@rohitvarkey We can use the same urls. A ```post_save``` handler can be used to populate the url field with the ids.

**Comment by rohitvarkey** [comment]
If we're using ids itself why bother complicating stuff so much?

**Comment by abhijithanilkumar** [comment]
So, is this fine? Or do you want me to move the URL assignment to the backend code? (In the views itself)

**Comment by rohitvarkey** [comment]
I'm not sure I fully understand what you're talking about here. :stuck_out_tongue: Use your best judgement.

**Comment by abhijithanilkumar** [comment]
Here, I've written a loop that iterates over the JSON in the html file. Instead, the same iteration can be done suing python in the views. So, if you want me to change it, I'll change. Otherwise, this is ready for merge. :stuck_out_tongue:

**Comment by rohitvarkey** [comment]
Merged! Good work @abhijithanilkumar and @vidit23.

Now please make one more PR for the day/month/year view.

**Pull request merged**
