### PR TITLE
News

### PR DESCRIPTION
**Pull request by vidit23**
I pulled from Jaidev's branch, just see

### CODE REVIEW

**Comment by rohitvarkey** [comment]
@vidit23 We need categorization in the news page. Check #1 details

**Comment by abhijithanilkumar** [comment]
@jaidevanoop @vidit23 Can you guys make a slight change in the homepage? The current homepage requires day and month separately for each event. Can it be changed so that the front end accepts the datetime field? Like the calendar does.

**Comment by abhijithanilkumar** [comment]
Never mind. It can be done in Django templates itself.

**Comment by jaidevanoop** [comment]
I haven't checked what the datetime looks like? But it can be processed to give the required output no? Ansu wanted the dates like that @abhijithanilkumar

**Comment by abhijithanilkumar** [comment]
I'll take care of it.

**Comment by vidit23** [comment]
Im going to make a new pull request, should be easier to merge.

**Pull request closed without merging**
