### PR TITLE
Project Intialization

### PR DESCRIPTION
**Pull request by abhijithanilkumar**
Edge Project Created!

### CODE REVIEW

**Comment by abhijithanilkumar** [comment]
@rohitvarkey  Have a look at this !

**Comment by rohitvarkey** [comment]
@abhijithanilkumar Can we keep the `.gitignore` and `travis.yml` files?

**Comment by rohitvarkey** [comment]
Also is this Python 2.7 compatible?

**Comment by rohitvarkey** [comment]
Actually let's use Python 3 for this.

**Comment by abhijithanilkumar** [comment]
I'll add back the `.gitignore` file. But `travis.yml` file was not present in the Initial Commit. And yeah, it is Python 2.7 compatible. [This](http://django-edge.readthedocs.org/en/latest/) link says so.

**Comment by rohitvarkey** [comment]
@abhijithanilkumar Don't keep the ones I generated in the first commit. Keep the ones generated by Edge. https://github.com/IE-NITK/NITK-Student-Council-Website/blob/70cca9d0c0bfb20fe21f04dbf38765eb82df2706/Student_Council_Website/.travis.yml
https://github.com/IE-NITK/NITK-Student-Council-Website/blob/70cca9d0c0bfb20fe21f04dbf38765eb82df2706/Student_Council_Website/.gitignore

**Comment by rohitvarkey** [comment]
This gitignore seems fine. Just add the travis file and we should be set.

**Comment by rohitvarkey** [comment]
I think this should work.
```
language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r Student_Council_Website/requirements.txt"
# command to run tests
script: 
- cd Student_Council_Website
- python manage.py test
```

**Comment by abhijithanilkumar** [comment]
Sorry for too many commits :stuck_out_tongue:

**Comment by rohitvarkey** [comment]
> Sorry for too many commits

You can rebase all the extra ones. :stuck_out_tongue:

**Comment by rohitvarkey** [comment]
Also add `[Build Status](https://travis-ci.org/IE-NITK/NITK-Student-Council-Website)` to the top of the README.md!

**Pull request merged**
